### ISSUE TITLE
Twitter Feed

### ISSUE THREAD

**Issue by maxdeviant** [yamigames/yamigames.github.io#2]
It looks like getting your tweets straight from the Twitter API is going to be a real pain for a frontend-only site, as the Twitter API requires authentication.

In order to add the Twitter feed we'll need to store the tweets in some other location that we can have unauthenticated read access from the site. We could use something like [Firebase](https://firebase.google.com/) to store the tweets in.

In terms of gathering the tweets, we could either have a lightweight server that gets the tweets and puts them in storage. Or we may be able to leverage something (like [IFTTT](https://ifttt.com/)) to have that perform the tweet collection.

**Comment by iamnbutler** [comment]
Interesting – and we can't serve them the way you would serve a list of any random @handle feed? Or is that not a thing anymore?

**Comment by maxdeviant** [comment]
That's not really a thing anymore. Twitter has locked down their API pretty hard, so pretty much every endpoint requires authentication now.

The [`GET statuses/user_timeline`](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline) endpoint, which seems like the one we would need to use, requires authentication and is subject to rate-limiting.

The sanctioned way to get a Twitter feed on a website is to use Twitter's [embedding functionality](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fiamnbutler&widget=Timeline), but then you have no control over the design.

**Comment by iamnbutler** [comment]
Mmk. Planning on de-pri'ing this for the mvp. It isn't overly important.

**Comment by iamnbutler** [comment]
Closing this out – if we decide to come back to it we can re-open.
